name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ] 

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x 
      
      - name: Publish
        run: dotnet publish "WebAssembly App/WebAssembly App.csproj" -c Release -o release --nologo
      
      # 關鍵步驟：這行會自動把你的 base href 改成正確的路徑，不影響你原本的檔案
      - name: Update base href
        run: sed -i 's/<base href="\/" \/>/<base href="\/WebAssembly-App\/" \/>/g' release/wwwroot/index.html
      
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot